### ISSUE TITLE
Working with static routes

### ISSUE THREAD

**Issue by kejace** [junjihashimoto/yesod-raml#1]
I can't seem to figure out how to use yesod-raml together with static routes, as per http://www.yesodweb.com/book/routing-and-handlers#routing-and-handlers_route_syntax

yaml doesn't want to parse my .raml file if I include them. On the other hand, it is unclear to me how to work with a sub-site together with yesod-raml.

Either support for _static_ within yesod-raml or an example using subsites would be greatly appreciated.

**Comment by junjihashimoto** [comment]
Currently yesod-raml does not support static routes.
[RAML spec](http://raml.org/spec.html) does not support subsites, too.

If we need static routes, I just think using both yesod-raml and yesod-route.
A example of  both yesod-raml and yesod-route  is below.

```
mkYesod "App" ([parseRoutes|
/static       StaticR   Static getStatic
|] <> [parseRamlRoutes|
#%RAML 0.8
title: Hoge API
baseUri: 'https://hoge/api/{version}'
version: v1
protocols: [ HTTPS ]
/user:
  /{userid}:
# handler tag is used.
    handler: HogeR
    get:
      description: Get user list
|]
)
```

If  you have good syntax idea for subsite, I can add static route definition in yesod-raml .

**Comment by kejace** [comment]
Thanks, this works just fine for my purposes.
