### ISSUE TITLE
Please add OPTIONS to Parser

### ISSUE THREAD

**Issue by kjameslubin** [junjihashimoto/yesod-raml#4]
The OPTIONS method is important for APIs in which e.g. JSON is being passed back and forth with AJAX. 
The current Parser appears not to support the OPTIONS method:
https://github.com/junjihashimoto/yesod-raml/blob/master/Yesod/Raml/Parser.hs#L34-L43.

I can probably just add the functionality by hand, but it would be nice to feed it back into the library to work with cabal / stack.

**Comment by junjihashimoto** [comment]
OK. I will add OPTIONS and other methods,
[RAML](http://raml.org/spec.html) supports following methods of both RFC2616 and RFC5789.

```
GET  
POST     
HEAD     
PUT  
DELETE   
TRACE    
CONNECT  
OPTIONS  
PATCH
```

By the way, I just read [yesod-book](http://www.yesodweb.com/book/restful-content) which does not include OPTIONS-method.

**Comment by junjihashimoto** [comment]
Update is done.

**Comment by kjameslubin** [comment]
Thanks for this
